config/routes.rb
Rails.application.routes.draw do

  resources :mountains, only: [:index]
  resources :trails, only: [:show]

  resources :mountains do
    resources :trails, only: [:index, :show]
  end

  resources :trails do
    resources :comments, only: [:new, :create]
  end

  resources :comments do
    resources :votes, only: [:create, :destroy]
  end

  resources :users, only: [:new, :show, :create]
  resources :sessions, only: [:new, :create, :destroy]

  root 'mountains#index'

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

  get 'about' => 'pages#show'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :trail
  belongs_to :user
  has_many :votes

  validates_presence_of :content, :trail_id, :user_id

end

app/models/mountain.rb
class Mountain < ActiveRecord::Base

  has_many :trails

  validates_presence_of :name, :city, :state

end

app/models/trail.rb
class Trail < ActiveRecord::Base

  belongs_to :mountain
  has_many :comments

  validates_presence_of :name, :mountain_id

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :comments
  has_many :votes

  validates :name, presence: true, length: {in: 8..20}
  validates :email, presence: true

  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :comment

  validates_presence_of :value, :user_id, :comment_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @user ||= User.find session[:user_id] if session[:user_id]
  end

  def authorize_user!
    redirect_to new_admin_session_path unless current_user.present?
  end

  def login user
    session[:user_id] = user.id
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @trail = Trail.find(params[:trail_id])
    @comment = Comment.new
    if request.xhr?
      render :_form, locals: {comment: @comment}, layout: false
    else
      render :new
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to trail_path(:id => params[:comment][:trail_id])
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    trail_id = @comment.trail.id
    @comment.destroy
    redirect_to trail_path(trail_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content,:user_id,:trail_id)
  end

end

app/controllers/mountain_controller.rb
class MountainsController < ActionController::Base

  def index
    @mountains = Mountain.all
  end

end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController

  def index
    @mountains = Mountain.all.order('name ASC')
    render :index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    render :about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
        login @user
        redirect_to root_path
    else
      flash[:notice] = "Invalid email or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def index
    @mountain = Mountain.find(params[:mountain_id])
    @trails = @mountain.trails.order('name ASC')
    render :index
  end

  def show
    @trail = Trail.find(params[:id])
    @comments = sort_comments_by_votes(@trail.comments)
    @comment = Comment.new
    render :show
  end

  private

  def sort_comments_by_votes(comments)
    comments.sort_by { |comment| [comment.votes.count, comment.created_at] }.reverse
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find_by(id: current_user.id)
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to root_path
    else
      flash[:notice] = "Invalid email or password"
      render new_user_path
    end
  end

  private

  def user_params
    user_params = params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @comment = Comment.find(params[:comment_id])
    @vote = Vote.new(value: 1, comment_id: params[:comment_id], user_id: current_user.id)
    if !@comment.votes.find_by(user_id: current_user.id) && @vote.save
      redirect_to trail_path(@vote.comment.trail.id)
    else
      @comment.votes.find_by(user_id: current_user.id).destroy
      redirect_to trail_path(@vote.comment.trail.id)
    end
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div class="comment-form">
<%= form_for @comment do |f| %>
  <p>
    <%= f.text_area :content %>
    <%= f.hidden_field :trail_id, :value => params[:trail_id] %>
  </p>
  <p>
    <%= f.submit 'Share' %>
  </p>
<% end %>
</div>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mountain Chat</title>

  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,300,700' rel='stylesheet' type='text/css'>

  <link href='https://fonts.googleapis.com/css?family=Catamaran:400,300,500,700' rel='stylesheet' type='text/css'>

</head>
<body>
<nav class="top-nav">
  <ul>
    <% if current_user %>
      <li class="left"><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Mountain Chat', root_path %></li>
      <% if @user %>
        <li class="right"><%= link_to("Logout", session_path(current_user), method: :delete) %></li>
      <% else %>
        <li class="right"><%= link_to("Profile", user_path(current_user)) %></li>
      <% end %>
      <% if @trail %>
        <li id="post" class="right"><%= link_to 'Post', new_trail_comment_path(@trail) %></li>
      <% end %>
    <% else %>
      <li class="left"><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Mountain Chat', root_path %></li>
      <li class="right"><%= link_to 'Login', new_session_path %></li>
    <% end %>
  </ul>
</nav>

<div class="main-container">
<%= yield %>
</div>

</body>
</html>

app/views/mountains/index.html.erb
<div>
<h2>List of Mountains</h2>
<hr>
</div>

<% @mountains.each do |mountain| %>
  <div>
    <h3><%= link_to mountain.name, mountain_trails_path(mountain) %></h3>
  </div>
<% end %>

app/views/pages/about.html.erb
<div class='about'>
<h4>Hi there!</h4>

<p>Mountain Chat connects skiers and snowboarders by crowdsourcing mountain conditions. Users are able to leave short notes about various trails, and upvote comments.</p>

<p>Currently functioning as a web application, upcoming Mountain Chat optimizions will focus on the mobile experience.</p>

<p>Your feedback is greatly appreciated! Feel free to reach out, and stay tuned for future improvements!</p>

<br>
<p>- <%= mail_to "zachschatz@gmail.com", "The Mountain Chat Team", :style => 'text-decoration: underline'%></p>
</div>

app/views/trails/_river.html.erb
<% @comments.each do |comment| %>
  <div class="vote-container">
    <% if current_user %>
      <%= link_to image_tag("snowflake.png", class: "snowflake"), {:controller => "votes",
          :action => "create",
          :comment_id => comment.id,
          :user_id => current_user.id,
          :value => "1"},
          :method => "post" %>
    <% else %>
      <%= link_to image_tag("snowflake.png", class: "snowflake") %>
    <% end %>
    <br>
    <%= comment.votes.sum(:value) %>
  </div>
  <div class="comment-container">
    <ul>
      <li><p class="comment"><%= comment.content%></li><br>
      <li>By: <%= comment.user.name %></li>
      <% if current_user && comment.user.id == current_user.id %>
      <li><%= link_to 'Delete', comment_path(comment.id), method: :delete %></p></li>
      <% else %>
        </p>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @comments.empty? %>
  <p class='about'>Been on this trail recently? <br> No one has posted yet, and others are wondering about the conditions!</p>
<% end %>

app/views/trails/index.html.erb
<div>
  <h3><%= @mountain.name %> Trails</h3>
  <hr>
</div>


<% @trails.each do |trail| %>
  <div>
    <h3><%= link_to trail.name, trail_path(trail) %></h3>
  </div>
<% end %>

<div class="go-back">
  <h4><%= link_to '&larr; Mountain List'.html_safe, root_path %></h4>
</div>

app/views/trails/show.html.erb
<div>
  <h2><%= @trail.name %></h2>
</div>

<div class="comment-form">
<%= form_for @comment do |f| %>
  <p>
    <%= f.text_area :content %>
    <%= f.hidden_field :trail_id, :value => params[:id] %>
  </p>
  <p>
    <%= f.submit 'Share' %>
  </p>
<% end %>
</div>

<div class="river">
<%= render 'river', :comments => @comments %>
</div>

<div class="go-back">
  <h4><%= link_to '&larr; Trails List'.html_safe, mountain_trails_path(@trail.mountain) %></h4>
</div>

app/views/users/new.html.erb
<h2>New User Signup:</h2>
<%= form_for User.new do |f| %>

  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>

  <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>

  <%= f.submit 'Create Account'%>

<% end %>

app/views/users/show.html.erb
<div class="profile-header">
  <h3><%= @user.name %> Posts</h3>
</div>

<% @user.comments.each do |comment| %>
  <div class="vote-container">
    <% if current_user %>
      <%= link_to image_tag("snowflake.png", class: "snowflake"), {:controller => "votes",
          :action => "create",
          :comment_id => comment.id,
          :user_id => current_user.id,
          :value => "1"},
          :method => "post" %>
    <% else %>
      <%= link_to image_tag("snowflake.png", class: "snowflake") %>
    <% end %>
    <br>
    <%= comment.votes.sum(:value) %>
  </div>
  <div class="comment-container">
    <ul>
      <li><p class="comment"><%= comment.content%></p></li><br>
      <li><%= comment.trail.name %> @ <%= comment.trail.mountain.name %></li>
    </ul>
  </div>
<% end %>

<% if @user.comments.empty? %>
  <p class='about'>Looks like you haven't posted yet! <br> Find your favorite trails and leave comments for other riders.</p>
<% end %>

<div class="go-back">
  <h4><%= link_to '&larr; Previous Page'.html_safe, request.referer.present? ? request.referer : default_path %></h4>
</div>